# projConfig.toml for xlCrypto_go

[meta]
    version = '0.1.0'

[project]
    name = 'xlCrypto_go'  # distro name
    package = 'xlCrypto_go'  # internal name
    main_lang = 'go'
    version = '0.6.15'
    version_date = '2017-11-13'
    author = 'Jim Dixon'
    author_email = 'jddixon@gmail.com'
    copyright = '2014-2017'
    description = 'Go crypto library for XLattice projects'
    dev_status = 'alpha'
    license = 'mit'
    relpath = 'go/src/github.com/jddixon/xlCrypto_go'
    state = 'shared'
    url = 'https://jddixon.github.io/xlCrypto_go'

[go]
    cmds=[]
